#set up file watcher
$watcher = New-Object System.IO.FileSystemWatcher

#define path to watch 
$downloads = "$env:USERPROFILE\Downloads"
$watcher.Path = $downloads

#watch all files
$watcher.Filter = "*"

#ignore subdirectories
$watcher.IncludeSubdirectories = $false

#enable watcher
$watcher.EnableRaisingEvents = $true

<#
Register-ObjectEvent links an event to an action

$watcher keeps track of all files in the downloads folder

when a new file is "Created", use action flag to run script block

pipe to Out-Null so that table output generated by Register-ObjectEvent is not printed to terminal
#>
Register-ObjectEvent $watcher "Created" -Action {
    #print to terminal that a new file was detcted
    Write-Host "`n[+] New file detected: $($Event.SourceEventArgs.Name)"

    #call python script
    python .\download_sorter.py
} | Out-Null

#print controls and instructions to terminal
Write-Host "Watching $downloads for new files"
Write-Host "Press Ctrl-C to exit"

#keep script running, checks for new file every second
while ($true) {
    Start-Sleep -Seconds 1
}